# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 543d13cc6bd43f19c69f4f6438259c1fb32dee4f8bbbb69b901193558d87315a9a1e09eebc48b98bc853eb58ec9b9e36299b2118c299900b31e5a2af3f07876c

test:
  secret_key_base: b1420746593ae63caa95b48efb59cbbf4d97ce06974683abe70d53e1d92807c8cd90173936ddc6620fe78acfad883b51a73d23856141980c92b5b78a7c485238

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
